I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 102, in script call
    call tutorial
  File "game/script.rpy", line 88, in script
    e "엘의회랑 별거아니죠?"
Exception: Sayer 'e' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 102, in script call
    call tutorial
  File "game/script.rpy", line 88, in script
    e "엘의회랑 별거아니죠?"
  File "E:\GameDevRenpy\renpy-8.1.1-sdk\renpy\ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "E:\GameDevRenpy\renpy-8.1.1-sdk\renpy\ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'e' is not defined.

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.1.23060707
YabbaKusoDemo_1 1.0
Mon Jun 19 14:14:39 2023
